configfile: "config/config.yaml"

include: "rules/prepare.smk"
include: "rules/ground_truth_view.smk"
include: "rules/aggregate_ground_truth_views.smk"
include: "rules/spike_sorting.smk"
include: "rules/sorting_view.smk"
include: "rules/aggregate_sorting_views.smk"
include: "rules/output.smk"

rule all:
    input:
        'output.md'
