recordings:
    - PAIRED_KAMPFF.paired_kampff.2014_11_25_Pair_3_0
    - PAIRED_KAMPFF.paired_kampff.2015_09_03_Pair_9_0A
    - PAIRED_KAMPFF.paired_kampff.2015_09_03_Pair_9_0B
    - PAIRED_KAMPFF.paired_kampff.c14
    - SYNTH_MAGLAND.synth_magland_noise10_K10_C4.001_synth
    - SYNTH_MAGLAND.synth_magland_noise10_K10_C4.002_synth
    - SYNTH_MAGLAND.synth_magland_noise10_K10_C4.003_synth